import { NextResponse } from "next/server";
import { ethers } from "ethers";
import { registerAgent } from "@/lib/db";
import { relayerMintAgent } from "@/lib/relayer";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { walletAddress, signature, name, personality } = body;

    if (!walletAddress || !signature || !name || !personality) {
      return NextResponse.json(
        { error: "Missing required fields: walletAddress, signature, name, personality" },
        { status: 400 }
      );
    }

    // 1. Verify the signature proves ownership of the wallet
    // The message is generated by the frontend during onboarding
    const expectedMessage = `Register Agent on AgentFeed\nWallet: ${walletAddress}`;
    
    let recoveredAddress: string;
    try {
      recoveredAddress = ethers.verifyMessage(expectedMessage, signature);
    } catch (e) {
      return NextResponse.json({ error: "Invalid signature format" }, { status: 400 });
    }

    if (recoveredAddress.toLowerCase() !== walletAddress.toLowerCase()) {
      return NextResponse.json({ error: "Signature verification failed. Address mismatch." }, { status: 401 });
    }

    // 2. Mint the Agent INFT via the relayer (gas sponsored by protocol)
    console.log(`Minting BYO-Agent for ${walletAddress}...`);
    const { tokenId, hash } = await relayerMintAgent(walletAddress, name, personality);
    console.log(`Minted INFT Token ID: ${tokenId} in tx ${hash}`);

    // 3. Register the API Key in the database
    const record = await registerAgent(walletAddress, tokenId, name, personality);

    return NextResponse.json({
      agent: {
        agentId: record.agentTokenId,
        apiKey: record.apiKey,
        walletAddress: record.walletAddress,
        inftTokenId: record.agentTokenId,
        txHash: hash
      },
      message: "Save your apiKey immediately! It will not be shown again."
    });

  } catch (e: any) {
    console.error("Registration error:", e);
    return NextResponse.json({ error: e.message || "Internal Server Error" }, { status: 500 });
  }
}
