import { NextResponse } from "next/server";
import { ethers } from "ethers";
import { registerAgent } from "@/lib/db";
import { relayerMintAgent } from "@/lib/relayer";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { walletAddress, signature, name, personality } = body;

    if (!walletAddress || !signature || !name || !personality) {
      return NextResponse.json(
        { error: "Missing required fields: walletAddress, signature, name, personality" },
        { status: 400 }
      );
    }

    // 1. Verify the signature proves ownership of the wallet
    // The message is generated by the frontend during onboarding
    const expectedMessage = `Register Agent on AgentFeed\nWallet: ${walletAddress}`;
    
    let recoveredAddress: string;
    try {
      recoveredAddress = ethers.verifyMessage(expectedMessage, signature);
    } catch (e) {
      return NextResponse.json({ error: "Invalid signature format" }, { status: 400 });
    }

    if (recoveredAddress.toLowerCase() !== walletAddress.toLowerCase()) {
      return NextResponse.json({ error: "Signature verification failed. Address mismatch." }, { status: 401 });
    }

    // 2. Mint the Agent INFT via the relayer (gas sponsored by protocol).
    // Also derives + funds the per-agent delegated wallet so the user just
    // needs one final tx to authorize it (single-sig instead of two).
    console.log(`Minting BYO-Agent for ${walletAddress}...`);
    const { tokenId, hash, delegatedAddress } = await relayerMintAgent(walletAddress, name, personality);
    console.log(`Minted INFT Token ID: ${tokenId} in tx ${hash} — delegated wallet ${delegatedAddress}`);

    // 3. Register the API Key + delegated wallet in the database (best-effort)
    let record;
    try {
      record = await registerAgent(walletAddress, tokenId, name, personality);
    } catch (e) {
      console.warn("Redis unavailable — apiKey not persisted, agent still minted:", (e as Error).message);
    }

    return NextResponse.json({
      agent: {
        agentId: tokenId,
        apiKey: record?.apiKey || null,
        walletAddress: walletAddress.toLowerCase(),
        inftTokenId: tokenId,
        txHash: hash,
        delegatedAddress, // the address the user should authorize via authorizeUsage
      },
      message: record?.apiKey
        ? "Save your apiKey immediately! It will not be shown again."
        : "Agent minted. Authorize the delegated wallet below.",
    });

  } catch (e: any) {
    console.error("Registration error:", e);
    return NextResponse.json({ error: e.message || "Internal Server Error" }, { status: 500 });
  }
}
